### ISSUE TITLE
REPL does not start on macOS

### ISSUE THREAD

**Issue by asbisen** [JuliaEditorSupport/zed-julia#11]
On macOS Sonoma 14.6.1 when I click on start REPL the editor is not able to start the REPL. And it goes in a loop trying to connect to the REPL. 

<img width="385" alt="Screenshot 2024-08-21 at 12 43 20 PM" src="https://github.com/user-attachments/assets/7167fd65-177b-4e6e-8898-d9683f887f29">

<img width="1165" alt="Screenshot 2024-08-21 at 12 43 48 PM" src="https://github.com/user-attachments/assets/caf5dd73-4fc8-4c94-b21a-dd56e6b30532">

Although, it's able to find the correct version of Julia. And is able to communicate with LanguageServer.jl.

<img width="1163" alt="Screenshot 2024-08-21 at 12 50 10 PM" src="https://github.com/user-attachments/assets/a0c3cb98-6342-4395-bff4-c2a81c068f4c">

**Comment by roman-timo** [comment]
I have the same issue. Julia seems running correct. Not much you can do to make wrong IJulia installation.. it's just using IJulia.

Can someone please explore this issue?

**Comment by bladerunnerwalrus** [comment]
I followed the 2 steps here: https://zed.dev/docs/repl 

Installed Julia, added it to PATH, can run `julia` from terminal, installed Julia extension in Zed, refreshed repl in Zed, but see no REPL button even after full reboot. 

My guess is it is not a full instruction? https://github.com/zed-industries/zed/issues/16024

**Comment by andrealati** [comment]
Just to flag that I am also having the same issue.  Julia and IJulia seem to be working correctly (i.e. I can run julia from terminal and as well as run jupyter notebooks with julia kernels).

**Comment by roman-timo** [comment]
@asbisen could you please add some labels for this issue so it would be visible
jupyter, repl, julia.. i guess

**Comment by ynhame** [comment]
I am having the same issue on linux using julia-1.10
I also tested other kernels: `python3` and `ark` and bouth of them worked.
updating IJulia didn't resolve the issue either.

**Comment by sprig** [comment]
Affected by the same. Julia+IJulia working, jupyter is working. Zed is able to run/connect to ipython and deno kernels but not to julia.

**Comment by liu20001028** [comment]
and Linux     jula-1.10
![Uploading QQ20240908-200054.png…]()
why   alway  this

**Comment by liu20001028** [comment]
me too      l am linux    julia 1.10    ERPL didnt use

**Comment by liu20001028** [comment]
REPL doesnt use in ZED  julia1.10.5

**Comment by Pangoraw** [comment]
Yes, this is tracked upstream in https://github.com/zed-industries/zed/issues/16024.
