### ISSUE TITLE
Add default `tab_size`

### ISSUE THREAD

**Issue by JosephTLyons** [JuliaEditorSupport/zed-julia#2]
Extensions are able to supply a handful of default settings to Zed. [Here's an example](https://github.com/zed-industries/zed/blob/247b0317b935ce5afebb69405d1a23c8cdb01914/extensions/prisma/languages/prisma/config.toml#L10). I think `tab_size = 4` could be added to this package.

**Comment by piechologist** [comment]
Closed with #1.

Thank you, @JosephTLyons !
