### ISSUE TITLE
LaTeX language injection

### ISSUE THREAD

**Issue by steffenhaug** [JuliaEditorSupport/zed-julia#20]
Just like we currently inject regex syntax into regexes, and SQL syntax into `SQLStrings`, I think it would be nice to have LaTeX language injection into [LaTeXStrings](https://github.com/JuliaStrings/LaTeXStrings.jl).

I tried to implement this before, but couldn't make it as nice as i wanted, because the `TeX` grammar can't deal with the surrounding `L"` and `L"""`. For the Markdown, Regex and SQL injections, it just so happens that those parsers deal with the surrounding quotations reasonably well, but in general we can't expect parsers of other languages to robustly handle quotation in Julia.

It would be nice if the tree-sitter parser created a child-node for string literals that contained _just the content of the string_, so it could be reparsed more easily.

I'm making this issue to gauge interest in this feature, make it searchable in case someone wonders why LaTeX strings are not highlighted, and to reference if we decide we need to bug the tree-sitter people about it.

**Comment by Pangoraw** [comment]
Other string macros to inject: 
 - `md` for markdown.
 - `html` for html.
I suppose Pycall has `py_str`.

For the single/triple string problem, neovim has the handy [`offset!`](https://neovim.io/doc/user/treesitter.html#treesitter-directive-offset) primitive in tree-sitter queries but zed does not have it.

**Comment by steffenhaug** [comment]
Those are good calls.

I didn't know about `offset!`, that's cool!

Maybe the Zed devs would be willing to provide `offset!`? I'm not sure what is best. On the one hand, tweaking the grammar would fix it for every editor ever, but on the other hand adding unnecessary nodes to the tree just to facilitate language injection, instead of representing the syntax of the language "as is", is kinda ugly if there are options.

**Comment by piechologist** [comment]
tree-sitter-julia v0.23.1 comes with a new `(content)` node that returns the string without the surrounding quotes.

That should allow injections for [LaTeXStrings](https://github.com/JuliaStrings/LaTeXStrings.jl). 

I've added `md` (that ignores quotes out of the box). Does anybody know what `html` and `py_str` expect?

**Comment by steffenhaug** [comment]
That's good news! I'm happy to work on some queries, but I'm fairly busy in the immediate future so if anyone else is eager they can go ahead.

**Comment by piechologist** [comment]
@steffenhaug: zed-julia 0.1.3 is out and you can update within Zed. All string macros mentioned above are available. `L"""\latex"""` works fine with the Zed LaTeX extension. (BTW, check out the docstrings 🎉.)

Feel free to open a new issue or PR if you miss something.

**Comment by steffenhaug** [comment]
Even better! :-)
