### ISSUE TITLE
Connection to Kernel not working 

### ISSUE THREAD

**Issue by theplatters** [JuliaEditorSupport/zed-julia#22]
When pressing Ctrl+Shift+Enter instead of executing the Julia Code Zed get's stuck on "Connecting to Kernel...".
When inspecting arunning sessions Julia 1.11 shows up.

![grafik](https://github.com/user-attachments/assets/358db394-9c42-453b-aa92-7264da659cea)

Platform:
EndeavourOS Linux x86_64
Kernel: 6.11.3-arch1-1
Julia 1.11.0

**Comment by Pangoraw** [comment]
See #11
