### ISSUE TITLE
Julia not available error message

### ISSUE THREAD

**Issue by guimarqu** [JuliaEditorSupport/zed-julia#7]
Hey,

Thank you for writing this extension.

I use zed 0.144.4 with this extension v0.1.2.

The extension was not working because it entered in the following `else` block.
https://github.com/JuliaEditorSupport/zed-julia/blob/8768aac33e9af04060c44b5bb2f29601beb164cb/src/julia.rs#L16-L18

Here is the log: 

```
2024-07-23T12:50:34.158792Z [INFO] Initializing default prettier with plugins {}
2024-07-23T12:50:34.158843Z [INFO] starting language servers for Julia: julia
2024-07-23T12:50:34.158871Z [INFO] starting language server "julia", path: "/Users/guimarqu/.julia/dev/MyPackage", id: 1
2024-07-23T12:50:34.158996Z [INFO] Initializing default prettier with plugins {}
2024-07-23T12:50:34.159025Z [INFO] starting language servers for Julia: julia
2024-07-23T12:50:34.165489Z [ERROR] failed to start language server "julia": julia not available
```

The error was due to the fact I didn't follow this [optional installation step](https://julialang.org/downloads/platform/#optional_add_julia_to_path).

```
sudo mkdir -p /usr/local/bin
sudo rm -f /usr/local/bin/julia
sudo ln -s /Applications/Julia-1.10.app/Contents/Resources/julia/bin/julia /usr/local/bin/julia
```

If I'm correct, I think we should mention in the readme that the optional installation step is mandatory to use zed-julia.
I can create a PR with the following sentence in the README.

```
If you are working on MacOS, you need to follow the [optional installation step](https://julialang.org/downloads/platform/#optional_add_julia_to_path) to get this extension working.
```

Best,

**Comment by Pangoraw** [comment]
we could change the error message to "julia not found in PATH"? Not sure if that would make sense on windows.

Also I would rather recommend installing with juliaup since that seems to add julia to path on macos directly.

**Comment by guimarqu** [comment]
I'm not sure about the "julia not found in PATH" message because the first thing I tried to do is adding `/Applications/Julia-1.10.app/Contents/Resources/julia/bin/julia` in my PATH variable. It didn't work. I had to create the symbolic link.
